# -*- coding: utf-8 -*-
"""Aula3subLPC1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QI4QOKh-RVAGmka12_hNB2Rql-Ufm2fm
"""

#ETE PORTO DIGITAL
#DISCIPLINA: LPC1
#PROFESSOR: CLOVES ROCHA
#ESTUDANTE: MARCOS A L DE ARAÚJO

print("Olá, ETE Porto Digital!")